accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', views.ELoginView.as_view(), name='login'),
    path('', views.forward),
    url(r'^logout/$', views.log_out),
    url(r'^dialogs/', include('users.urls')),
    url(r'^registration/$', views.registration), # пока не работает
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from accounts.views import ELoginView

urlpatterns = [
    url(r'^login/', ELoginView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    path('', include('accounts.urls'))
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'users'
urlpatterns = [
    path('', login_required(views.DialogsView.as_view()), name='dialogs'),
    url(r'^create/(?P<user_id>\d+)/$', login_required(views.CreateDialogView.as_view()), name='create_dialog'),
    url(r'^(?P<chat_id>\d+)/$', login_required(views.MessagesView.as_view()), name='messages'),
]

accounts/models.py
from django.db import models

# Create your models here.

users/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class ChatManager(models.Manager):
    use_for_related_fields = True

    def unreaded(self, user=None):
        qs = self.get_queryset().exclude(last_message__isnull=True).filter(last_message__is_readed=False)
        return qs.exclude(last_message__author=user) if user else qs


class Chat(models.Model):
    members = models.ManyToManyField(User, verbose_name=_("Участник"))
    objects = ChatManager()

    def get_absolute_url(self):
        return reverse('users:messages', (), {'chat_id': self.pk})


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name=_("Чат"), on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name=_("Пользователь"), on_delete=models.CASCADE)
    message = models.TextField(_("Сообщение"))
    pub_date = models.DateTimeField(_('Дата сообщения'), default=timezone.now)
    is_readed = models.BooleanField(_('Прочитано'), default=False)
    objects = ChatManager()

    class Meta:
        ordering = ['pub_date']

    def __str__(self):
        return self.message

accounts/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=4)

users/forms.py
from django.forms import ModelForm
import django.forms as forms
from .models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

accounts/views.py
# -*- coding: utf-8 -*-
from urllib.parse import urlparse
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib import auth
from django.template.context_processors import csrf
from django.urls import reverse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.utils.http import is_safe_url, urlunquote
from .forms import RegisterForm
from users import models


def get_next_url(request):
    next = request.META.get('HTTP_REFERER')
    if next:
        next = urlunquote(next)
    if not is_safe_url(url=next, allowed_hosts=request.get_host()):
        next = '/'
    return next


class ELoginView(View):

    def get(self, request):
        if auth.get_user(request).is_authenticated:
            return redirect('/dialogs/')
        else:
            context = create_context_username_csrf(request)
            return render(request, 'accounts/login.html', context=context)

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            next = urlparse(get_next_url(request)).path
            return redirect(next)
        context = create_context_username_csrf(request)
        context['login_form'] = form
        return render(request, 'accounts/login.html', context=context)


def create_context_username_csrf(request):
    context = {}
    context.update(csrf(request))
    context['login_form'] = AuthenticationForm
    return context


def log_out(request):
    logout(request)
    return redirect('/accounts/login/')


def forward(request):
    return redirect('/accounts/login/')


def registration(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            name = form.cleaned_data['username']
        user = models.User.objects.create_user(password=password, username=name)
        user.save()
        return HttpResponseRedirect('/accounts/login/')
    else:
        form = RegisterForm()
    return render(request, 'accounts/registration.html', {'form': form})

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.contrib.auth.models import User
from users.forms import MessageForm
from .models import Chat, Message


class DialogsView(View):
    def get(self, request):
        users_list = User.objects.all().filter(is_superuser__exact=0).exclude(id__exact=request.user.id)
        chats = Chat.objects.filter(members__in=[request.user.id])
        unreaded = {}
        for chat in chats:
            unreaded[chat.id] = (Message.objects.filter(is_readed__exact=False, chat_id__exact=chat.id).exclude(
                author_id__exact=request.user.id).count())
        context = {
            'user_profile': request.user,
            'chats': chats,
            'unrdms': unreaded,
            'users': users_list
        }

        return render(request, 'users/dialogs.html', context)

class CreateDialogView(View):
    def get(self, request, user_id):
        chats = Chat.objects.filter(members__in=[request.user.id, user_id])
        if chats.count() == 0:
            chat = Chat.objects.create()
            chat.members.add(request.user)
            chat.members.add(user_id)
        else:
            chat = chats.first()
        id = str(chat.id)
        url = '/dialogs/' + id + '/'
        return HttpResponseRedirect(url)


class MessagesView(View):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
            if request.user in chat.members.all():
                chat.message_set.filter(is_readed=False).exclude(author=request.user).update(is_readed=True)
            else:
                chat = None
        except Chat.DoesNotExist:
            chat = None
        context = {
                'user_profile': request.user,
                'chat': chat,
                'form': MessageForm(),
        }
        return render(request, 'users/messages.html', context)

    def post(self, request, chat_id):
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.chat_id = chat_id
            message.author = request.user
            message.save()
            url = '/dialogs/'+chat_id+'/'
            return HttpResponseRedirect(url)
        context = {'chat_id': chat_id}
        return render(request, 'users/messages.html', context=context)

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block head %}
{% endblock %}
{% block content %}
    {% block page %}
    {% endblock page %}
    {% block sidebar %}
    {% endblock %}
{% endblock content %}
{% block footer %}
{% endblock %}
</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Войти</title>
</head>
<body>
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="col-md-offset-3 col-md-6 voffset-60">
        <h1>Войти на сайт</h1>
        {% include 'accounts/login_widget.html' %}
    </div>
{% endblock %}
</body>
</html>

accounts/templates/accounts/login_widget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Войти</title>
</head>
<body>
{% load staticfiles %}
<link rel="stylesheet" href="{% static '/accounts/css/bootstrap.min.css'%}">
<script src="/static/accounts/js/bootstrap.min.js"></script>

<form id="contact_form" action="{% url 'accounts:login' %}" method="post">
    {% load bootstrap3 %}
    {% csrf_token %}
    {% bootstrap_form login_form %}
    {% buttons %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Войти</button>
            <a class="btn btn-primary" href="/accounts/registration/" role="button" style="">Зарегистрироваться</a>
            <p></p>
            <p><a class="btn btn-outline-primary" href="/admin/" role="button" style="">Войти как админ</a></p>
        </div>
    {% endbuttons %}
</form>
</body>
</html>

accounts/templates/accounts/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load staticfiles %}
<link rel="stylesheet" href="{% static '/accounts/css/bootstrap.min.css'%}">
<script src="/static/accounts/js/bootstrap.min.js"></script>
<div class="container">
    <br>
        <div class="panel">
            {% load bootstrap3 %}
            <div id="message_form">
                <form id="message-form" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <br><br>
                    <button type="submit" class="btn btn-outline-primary">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

users/templates/users/dialogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Диалоги</title>
</head>
<body>
{% load staticfiles %}
<link rel="stylesheet" href="{% static '/users/css/bootstrap.min.css'%}" id="bootstrap-css">
<script src="/static/users/js/bootstrap.min.js"></script>
<div class="container">
    <div class="jumbotron">
        <div class="panel">
            {% load bootstrap3 %}
            {% load tz %}
            {% load i18n %}
            {% load custom_tags %}
            {% if chats.count == 0 %}
                <div class="panel panel-body">{% trans "Нет ни одного начатого диалога. Выберите пользователя" %}
                    <br>
                    {% for user in users %}
                        <p><a href="create/{{ user.id }}/">{{ user }}</a></p>
                    {% endfor %}
                </div>
            {% else %}
                {% trans "Выберите пользователя" %}
                <br>
                {% for user in users %}
                    <p><a href="create/{{ user.id }}/">{{ user }}</a></p>
                {% endfor %}
                {% trans "Последние диалоги" %}
                {% for chat in chats %}
                <div class="list-group-item">
                    {% with last_message=chat.message_set.last mes=chat.is_readed_set.count key=chat.id %}
                        {% get_companion user chat as companion %}
                            <div class="reply-body">
                                <ul class="list-inline">
                                    <li class="drop-left-padding">
                                        <strong class="list-group-item-heading"><a href="{{ chat.id }}/">{{ companion.username }}</a></strong>
                                        {%for key, value in unrdms.items  %}
                                            {% if key == chat.id %}
                                                {% if value != 0 %}
                                                    {% trans "Новых сообщений: " %}{{ value }}
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    </li>
                                    <li class="pull-right text-muted"><small>{{ last_message.pub_date|utc }}</small></li>
                                </ul>
                                <div class="row">
                                  <div class="col-12 text-truncate">
                                    {{ last_message.message|safe|striptags }}
                                  </div>
                                </div>
                            </div>
                    {% endwith %}
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <p><a class="btn btn-primary" href="/logout/" role="button" style="">Logout</a></p>
</div>
</body>
</html>

users/templates/users/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% url 'users:profile' message_item.author.username as the_user_url%}
{% load tz %}
<div class="list-group-item {% if not message_item.is_readed %}unreaded{% endif %}">
    <a href="{{ the_user_url }}"></a>
    <div class="reply-body">
        <ul class="list-inline">
            <li class="drop-left-padding">
                <strong class="list-group-item-heading">{{ message_item.author.username }}</strong>
            </li>
            <li class="pull-right text-muted"><small>{{ message_item.pub_date|utc }}</small></li>
        </ul>
        <div>{{ message_item.message|safe }}</div>
    </div>
</div>
</body>
</html>

users/templates/users/messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Чат</title>
</head>
<body>
{% load staticfiles %}
<link rel="stylesheet" href="{% static '/users/css/bootstrap.min.css'%}" id="bootstrap-css">
<script src="/static/users/js/bootstrap.min.js"></script>
{% load bootstrap3 %}
{% load i18n %}
<div class="container">
    <div class="jumbotron">
    {% if not chat %}
        <div class="panel panel-body">
            {% trans "Невозможно начать беседу. Не найден пользователь или вы не имеете доступа к данной беседе." %}
            <br><p><a href="/dialogs/">Назад к списку контактов</a></p>
        </div>
    {% else %}
        {% load tz %}
        <p><a href="/dialogs/">Назад к списку контактов</a></p>
        {% if chat %}
            <div id="messages" class="panel">
                <div id="innerMessages">
                    {% for message in chat.message_set.all %}
                        {% include 'users/message.html' with message_item=message %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <br>
        <div id="message_form">
            <form id="message-form" method="post">
                {% csrf_token %}
                {{ form }}
                <br>
                <button type="submit" class="btn btn-outline-primary">Отправить</button>
            </form>
        </div>
    {% endif %}
    </div>
    <p><a class="btn btn-primary" href="/logout/" role="button" style="">Logout</a></p>
</div>
</body>
</html>
